#!/usr/bin/env python3
"""Install EvoOntology into Oh My Pi (OMP) for the current user.

Usage:
    uv run --project <clone> python scripts/install_omp.py
    uv run --project <clone> python scripts/install_omp.py --agent-dir <dir> --store <dir> --uv <path>

What it does (idempotent; safe to re-run):
  1. Registers the ``evo-semantic`` stdio MCP server in ``<agent-dir>/mcp.json``
     (default ``~/.omp/agent``), merging only that one entry and preserving
     every unrelated field and server.
  2. Writes the OMP extension wrapper ``evo-capture.ts`` into
     ``<agent-dir>/extensions/``. The wrapper imports the real extension from
     this checkout and calls its default export with install-time
     ``{store, uv}`` defaults.
  3. Symlinks the three ontology skills (``build-ontology``,
     ``evolve-ontology``, ``explore-ontology``) into ``<agent-dir>/skills/``.
  4. Records an install manifest at ``<agent-dir>/evoontology-install.json``.

Precedence is explicit runtime env first, consistently on both paths: an
absolute ``$EVO_ONTOLOGY_STORE`` / ``$EVO_ONTOLOGY_UV`` in the server or
extension process environment wins over the baked-in install defaults, which
win over the HOME-derived defaults (``~/.omp/ontologies/shared``, ``uv`` via
``PATH``). The install-resolved store is always persisted in the MCP entry
``--store`` args and the extension wrapper defaults, so a later launch
without env resolves identically; runtime env still overrides both.

Defaults derive from the current user's HOME (never a hardcoded personal
path): the checkout from this script's location, ``uv`` from ``--uv`` /
``$EVO_ONTOLOGY_UV`` / ``PATH`` (verified executable), the agent dir from
``~/.omp/agent``, and the store from ``--store`` / absolute
``$EVO_ONTOLOGY_STORE`` / ``~/.omp/ontologies/shared``.

Any conflict is reported before anything is mutated: a foreign
``evo-semantic`` entry, an unrelated file at the extension/skills paths, or
an unreadable ``mcp.json`` aborts the install with no changes. An older own
registration for this same clone (via ``evoontology.runtime.mcp_server``,
with or without ``--project-aware``/``--store``) is migrated to the fresh
``evoontology.runtime.omp_server`` shape.

The installer writes no ontology state (no state.json, project.json, or
ontology versions); it only ensures the store directory exists.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from pathlib import Path

SERVER_MODULE = "evoontology.runtime.omp_server"
LEGACY_SERVER_MODULE = "evoontology.runtime.mcp_server"
STORE_ENV_VAR = "EVO_ONTOLOGY_STORE"
UV_ENV_VAR = "EVO_ONTOLOGY_UV"
MANIFEST_NAME = "evoontology-install.json"

EXTENSION_TARGET = "evo-capture.ts"
EXTENSION_SOURCE = Path("integrations") / "omp" / "evo-capture.ts"
EXTENSION_MARKER = "Generated by EvoOntology scripts/install_omp.py"
SKILL_NAMES = ("build-ontology", "evolve-ontology", "explore-ontology")
SKILL_SOURCE_BASE = Path("plugins") / "evoontology-codex" / "skills"


class InstallError(Exception):
    """A preflight conflict or environment problem; nothing was mutated."""


def clone_root() -> Path:
    root = Path(__file__).resolve().parent.parent
    if not (root / "pyproject.toml").is_file():
        raise InstallError(f"clone sentinel missing: {root / 'pyproject.toml'}")
    if not (root / "evoontology" / "trajectory" / "omp_capture.py").is_file():
        raise InstallError("clone sentinel missing: evoontology/trajectory/omp_capture.py")
    return root


def resolve_uv(explicit: str | None) -> str:
    for candidate in (explicit, os.environ.get(UV_ENV_VAR, "")):
        if candidate and candidate.strip():
            return _require_executable(candidate.strip())
    found = shutil.which("uv")
    if found:
        return found
    raise InstallError(
        "uv executable not found: pass --uv <path>, set $EVO_ONTOLOGY_UV, "
        "or put uv on PATH"
    )


def _require_executable(candidate: str) -> str:
    path = Path(candidate).expanduser()
    if path.is_absolute() or os.sep in candidate:
        resolved = path.resolve()
        if not resolved.is_file() or not os.access(resolved, os.X_OK):
            raise InstallError(f"uv is not executable: {candidate}")
        return str(resolved)
    found = shutil.which(candidate)
    if found is None:
        raise InstallError(f"uv is not executable: {candidate}")
    return found


def resolve_agent_dir(explicit: str | None) -> Path:
    if explicit and explicit.strip():
        return Path(explicit.strip()).expanduser().resolve()
    return (Path.home() / ".omp" / "agent").resolve()


def resolve_store(explicit: str | None) -> Path:
    if explicit and explicit.strip():
        return Path(explicit.strip()).expanduser().resolve()
    override = os.environ.get(STORE_ENV_VAR, "").strip()
    if override:
        candidate = Path(override).expanduser()
        if not candidate.is_absolute():
            raise InstallError(
                f"${STORE_ENV_VAR} must be an absolute path, got {override!r}"
            )
        return candidate.resolve()
    return (Path.home() / ".omp" / "ontologies" / "shared").resolve()


def expected_entry(*, clone: Path, uv: str, store: Path) -> dict:
    # The install-resolved store is always persisted: runtime env still wins
    # inside omp_server, so baking it can never shadow an explicit override.
    args = [
        "run",
        "--offline",
        "--no-sync",
        "--project",
        str(clone),
        "python",
        "-m",
        SERVER_MODULE,
        "--store",
        str(store),
    ]
    return {
        "type": "stdio",
        "command": uv,
        "args": args,
        "env": {"PYTHONIOENCODING": "utf-8", "PYTHONUTF8": "1"},
        "enabled": True,
        "timeout": 120000,
    }


def _entry_clone(entry: dict) -> str | None:
    """Return the ``--project`` clone path of an evo-semantic entry, if any."""
    try:
        args = entry.get("args")
        if not isinstance(args, list):
            return None
        for i, token in enumerate(args):
            if token == "--project" and i + 1 < len(args):
                value = args[i + 1]
                if isinstance(value, str) and value.strip():
                    return value.strip()
    except (AttributeError, IndexError):
        return None
    return None


def _entry_modules(entry: dict) -> list[str]:
    args = entry.get("args")
    if not isinstance(args, list):
        return []
    return [t for t in args if isinstance(t, str) and t.startswith("evoontology.")]


def is_own_entry(entry: dict, clone: Path) -> bool:
    """True for entries this installer owns: this clone + a known module."""
    if not isinstance(entry, dict):
        return False
    raw = _entry_clone(entry)
    if raw is None:
        return False
    try:
        same = Path(raw).expanduser().resolve() == clone.resolve()
    except OSError:
        same = raw == str(clone)
    if not same:
        return False
    return any(m in (SERVER_MODULE, LEGACY_SERVER_MODULE) for m in _entry_modules(entry))


def load_mcp(path: Path) -> dict:
    if not path.exists():
        return {"mcpServers": {}}
    if not path.is_file():
        raise InstallError(f"{path} exists and is not a file")
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise InstallError(f"cannot read {path} as JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise InstallError(f"{path} must contain a JSON object")
    servers = data.get("mcpServers", {})
    if not isinstance(servers, dict):
        raise InstallError(f"{path}: 'mcpServers' must be an object")
    return data


def _read_manifest(agent_dir: Path) -> dict:
    manifest = agent_dir / MANIFEST_NAME
    if not manifest.is_file():
        return {}
    try:
        data = json.loads(manifest.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    return data if isinstance(data, dict) else {}


def preflight(
    *,
    agent_dir: Path,
    clone: Path,
    store: Path,
    uv: str,
    mcp_data: dict,
) -> tuple[dict, Path, Path, list[tuple[Path, Path]]]:
    """Validate everything before mutating; return (entry, ext, src, skills)."""
    servers = mcp_data.setdefault("mcpServers", {})
    existing = servers.get("evo-semantic")
    want = expected_entry(clone=clone, uv=uv, store=store)
    if existing is not None:
        if not isinstance(existing, dict):
            raise InstallError("mcp.json 'evo-semantic' entry must be an object")
        if not is_own_entry(existing, clone):
            raise InstallError(
                "mcp.json already has an unrelated 'evo-semantic' entry; "
                "remove or rename it before installing"
            )

    ext_source = clone / EXTENSION_SOURCE
    if not ext_source.is_file():
        raise InstallError(f"installer source missing: {ext_source}")
    ext_dest = agent_dir / "extensions" / EXTENSION_TARGET
    if os.path.lexists(ext_dest):
        if ext_dest.is_symlink():
            try:
                if Path(os.path.realpath(ext_dest)) == ext_source.resolve():
                    pass  # ours from a previous version; replace with wrapper
                else:
                    raise InstallError(
                        f"{ext_dest} is a symlink to another target; "
                        "remove it before installing"
                    )
            except OSError as exc:
                raise InstallError(f"cannot resolve {ext_dest}: {exc}") from exc
        elif ext_dest.is_file():
            manifest = _read_manifest(agent_dir)
            if manifest.get("extension_wrapper") != str(ext_dest):
                raise InstallError(
                    f"{ext_dest} already exists and is not our install; "
                    "move it aside before installing"
                )
        else:
            raise InstallError(
                f"{ext_dest} already exists and is not our install; "
                "move it aside before installing"
            )

    manifest = _read_manifest(agent_dir)
    owned_copies: set[str] = set(manifest.get("copies", []))
    links: list[tuple[Path, Path]] = []
    for name in SKILL_NAMES:
        src = clone / SKILL_SOURCE_BASE / name
        if not src.is_dir():
            raise InstallError(f"installer source missing: {src}")
        dest = agent_dir / "skills" / name
        if os.path.lexists(dest):
            if dest.is_symlink():
                try:
                    if Path(os.path.realpath(dest)) != src.resolve():
                        raise InstallError(
                            f"{dest} is a symlink to another target; "
                            "remove it before installing"
                        )
                except OSError as exc:
                    raise InstallError(f"cannot resolve {dest}: {exc}") from exc
            elif str(dest) in owned_copies:
                pass  # ours from a copy fallback; refresh below
            else:
                raise InstallError(
                    f"{dest} already exists and is not our install; "
                    "move it aside before installing"
                )
        links.append((dest, src))
    return want, ext_dest, ext_source, links


def render_extension_wrapper(*, source: Path, store: Path, uv: str) -> str:
    uri = source.resolve().as_uri()
    return (
        f"// {EXTENSION_MARKER} — do not hand-edit. Re-run the installer to update.\n"
        "// Imports the real extension from the checkout and applies install-time\n"
        "// {store, uv} defaults. Explicit process env (EVO_ONTOLOGY_STORE /\n"
        "// EVO_ONTOLOGY_UV) takes precedence at runtime inside the extension.\n"
        f'import baseExtension from "{uri}";\n'
        f'export * from "{uri}";\n'
        "const INSTALL_DEFAULTS = {\n"
        f'  store: {json.dumps(str(store))},\n'
        f'  uv: {json.dumps(uv)},\n'
        "};\n"
        "export default function evoCaptureExtension(pi) {\n"
        "  return baseExtension(pi, INSTALL_DEFAULTS);\n"
        "}\n"
    )


def create_link(dest: Path, src: Path, *, manifest_copies: list[str]) -> str:
    dest.parent.mkdir(parents=True, exist_ok=True)
    if os.path.lexists(dest):
        if dest.is_symlink():
            return "kept"
        if str(dest) in manifest_copies:
            if dest.is_dir():
                shutil.rmtree(dest)
            else:
                dest.unlink()
        else:  # pragma: no cover - preflight rejects this
            raise InstallError(f"refusing to overwrite {dest}")
    try:
        os.symlink(src, dest)
        return "symlink"
    except OSError as exc:
        # No symlink privilege (e.g. Windows): copy skills only with ownership
        # tracking; anything else is an explicit error, never fake success.
        if src.is_dir():
            try:
                shutil.copytree(src, dest)
                manifest_copies.append(str(dest))
                return "copy"
            except OSError:
                pass
        raise InstallError(
            f"cannot link {dest} -> {src} ({exc}); on Windows enable "
            "Developer Mode or run as administrator, then re-run the installer"
        ) from exc


def install(
    *,
    agent_dir: Path,
    clone: Path,
    store: Path,
    uv: str,
) -> dict:
    mcp_path = agent_dir / "mcp.json"
    mcp_data = load_mcp(mcp_path)
    want, ext_dest, ext_source, links = preflight(
        agent_dir=agent_dir,
        clone=clone,
        store=store,
        uv=uv,
        mcp_data=mcp_data,
    )

    # All checks passed: mutate now.
    store.mkdir(parents=True, exist_ok=True)
    old_manifest = _read_manifest(agent_dir)
    manifest_copies: list[str] = list(old_manifest.get("copies", []))

    methods: dict[str, str] = {}
    ext_dest.parent.mkdir(parents=True, exist_ok=True)
    if ext_dest.is_symlink():
        ext_dest.unlink()
    ext_dest.write_text(
        render_extension_wrapper(source=ext_source, store=store, uv=uv),
        encoding="utf-8",
    )
    methods[str(ext_dest)] = "wrapper"
    for dest, src in links:
        methods[str(dest)] = create_link(dest, src, manifest_copies=manifest_copies)

    mcp_data["mcpServers"]["evo-semantic"] = want
    agent_dir.mkdir(parents=True, exist_ok=True)
    mcp_path.write_text(json.dumps(mcp_data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    (agent_dir / MANIFEST_NAME).write_text(
        json.dumps(
            {
                "clone": str(clone),
                "store": str(store),
                "uv": uv,
                "server_module": SERVER_MODULE,
                "extension_wrapper": str(ext_dest),
                "copies": manifest_copies,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    return {"mcp.json": str(mcp_path), "store": str(store), "links": methods}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--agent-dir", default=None, help="OMP agent dir (default ~/.omp/agent)")
    parser.add_argument("--store", default=None, help="Shared ontology store (default $EVO_ONTOLOGY_STORE or ~/.omp/ontologies/shared)")
    parser.add_argument("--uv", default=None, help="uv executable (default $EVO_ONTOLOGY_UV or PATH)")
    args = parser.parse_args(argv)
    try:
        result = install(
            agent_dir=resolve_agent_dir(args.agent_dir),
            clone=clone_root(),
            store=resolve_store(args.store),
            uv=resolve_uv(args.uv),
        )
    except InstallError as exc:
        print(f"install_omp: error: {exc}", file=sys.stderr)
        return 1
    print(f"install_omp: agent mcp.json updated: {result['mcp.json']}")
    print(f"install_omp: store: {result['store']}")
    for dest, method in sorted(result["links"].items()):
        print(f"install_omp: {method}: {dest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
